events {}

http {
	include mime.types;

	server {
		listen 443 ssl;      # IPv4
		listen [::]:443 ssl; # IPv6

		server_name juljin.42.fr;

		ssl_certificate /etc/nginx/ssl/juljin.crt;
		ssl_certificate_key /etc/nginx/ssl/juljin.key;
		ssl_protocols TLSv1.3;

		root /var/www/html;
		index index.php index.html index.htm;

		# Bonus: Static Site (Digital Clock)
		location /clock/ {
			proxy_pass http://static_site:8081/;
			proxy_set_header Host $host;
		}

		# Bonus: Adminer (Database GUI)
		location /adminer/ {
			proxy_pass http://adminer:8080/;
			proxy_set_header Host $host;
		}

		# Forward PHP requests to the WordPress container
		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
		}

		# Primary fallback routing for WordPress
		location / {
			try_files $uri $uri/ /index.php?$args;
		}
	}
}

