# --- Services layer -------------------------------------------------------- // 

services:
  # NGINX: Reverse Proxy & TLS encryption entrypoint
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html

  # MariaDB: Relational database engine storing WordPress data 
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password

  # WordPress: FastCGI server generatic dynamic website content
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  # Static Site: Digital Clock (Bonus)
  static_site:
    build: requirements/bonus/static_site
    container_name: static_site
    restart: always
    networks:
      - inception

  # Adminer: Database Management GUI (Bonus)
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception

  # Redis: In-Memory Object Cache (Bonus)
  redis:
    build: requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception

  # FTP: File Transfer Protocol Server (Bonus)
  vsftpd:
    build: requirements/bonus/vsftpd
    container_name: vsftpd
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    secrets:
      - vsftpd_password

  # cAdvisor: Live Container Monitoring (Bonus)
  cadvisor:
    build: requirements/bonus/cadvisor
    container_name: cadvisor
    restart: always
    # We must mount the physical host machine's system files so cAdvisor can read the live metrics
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8082:8080" # Exposed externally on port 8082
    networks:
      - inception

# --- Networking layer ------------------------------------------------------ // 

networks:
  inception:
    driver: bridge # Virtual Software Router

# --- Volumes layer --------------------------------------------------------- //

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none # Not use the default hidden volume formatting
      o: bind # Force to bind to a physical folder
      device: /home/${USER_LOGIN}/data/mariadb

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_LOGIN}/data/wordpress


# --- Secrets layer --------------------------------------------------------- //

secrets:
  db_password:
    file: ../secrets/db_password.txt

  db_root_password:
    file: ../secrets/db_root_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_user_password:
    file: ../secrets/wp_user_password.txt

  vsftpd_password:
    file: ../secrets/vsftpd_password.txt
